apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: root-ca-bundle
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  sources:
    - secret:
        name: root-ca
        key: tls.crt
  target:
    configMap:
      key: ca.crt
    namespaceSelector:
      matchLabels:
        shortlink-org/trust-bundle: "enabled"
