apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root-ca-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ca:
    # CA keypair stored in {{ .Release.Namespace }}/root-ca
    secretName: root-ca
