apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: mesh-otel
spec:
  tracing:
    - providers:
        - name: "otel-tracing"
      randomSamplingPercentage: 100.00
  # accessLogging:
  #   - providers:
  #       - name: otel
