apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shortlink-best
  namespace: istio-ingress
spec:
  secretName: shortlink-best-tls
  issuerRef:
    name: cert-manager-production
    kind: ClusterIssuer
  dnsNames:
    - shortlink.best
    - "*.shortlink.best"
