apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: external-gateway
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-production
spec:
  gatewayClassName: istio
  listeners:
    # HTTP listener (порт 80) — принимает все домены shortlink.best и поддомены
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All

    # HTTPS listener (порт 443) — принимает все домены shortlink.best и поддомены
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: shortlink-best-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
