apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: internal-gateway
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same

    - name: grpc
      port: 50051
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: internal-gateway-tls
      allowedRoutes:
        namespaces:
          from: All

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-gateway-cert
spec:
  secretName: internal-gateway-tls
  issuerRef:
    name: ca-issuer
  commonName: internal-gateway-istio.{{ .Release.Namespace }}.svc.cluster.local
  dnsNames:
    - internal-gateway-istio
    - internal-gateway-istio.{{ .Release.Namespace }}
    - internal-gateway-istio.{{ .Release.Namespace }}.svc
    - internal-gateway-istio.{{ .Release.Namespace }}.svc.cluster.local
  usages:
    - digital signature
    - key encipherment
    - server auth

---

apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: internal-mtls
spec:
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: internal-gateway
  mtls:
    mode: PERMISSIVE
