apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: internal-gateway
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same

    - name: grpc
      port: 50051
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: internal-gateway-tls
      allowedRoutes:
        namespaces:
          from: Same

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-gateway-cert
spec:
  secretName: internal-gateway-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: internal-gateway.shortlink
  dnsNames:
    - "*.shortlink"
