{{/* vim: set filetype=mustache: */}}

{{ include "shortlink-common.ServiceAccount" . }}

{{ include "shortlink-common.Deployment" . }}

{{ include "shortlink-common.Ingress" . }}

{{ include "shortlink-common.http_route" . }}

{{ include "shortlink-common.Service" . }}

{{ include "shortlink-common.NetworkPolicy" . }}
