apiVersion: v1
kind: Secret
metadata:
  name: testkube-user
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  CONSOLE_ACCESS_KEY: {{ .Values.BUCKET_PASSWORD | b64enc }}
  CONSOLE_SECRET_KEY: {{ .Values.BUCKET_PASSWORD | b64enc }}
