BUCKET_PASSWORD: ENC[AES256_GCM,data:zM7ZdCSLcIoSBTqpQJV94HqNU7o=,iv:q1hEH/tWyenHTLqV28Gk8/EbHruUmPKsmoCk10u+R74=,tag:PCp7EKZzbAhMC6w3S3NxMA==,type:str]
MINIO_ROOT_USER: ENC[AES256_GCM,data:CBBA3s2acq3YRJsgj2cbZg==,iv:slTDDJs9NcBoWMeiIGQDDQQhm+ig/cSRMayvgfHid18=,tag:HNltV27CWyMKUYWAl+il4w==,type:str]
MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:9kXyYW2OwXmj3X5LhGylaaBTjsKasuLUOutl9zpksn0=,iv:dZ29LS+c/vt8tKhftjh84RRQPQus1uwIUqAQWCWM/I8=,tag:ND5skOBaxBWnEp3f/n0vsg==,type:str]
EnvConfig: ENC[AES256_GCM,data:zKH3aNJhuUJmh4SVbkwIXxDCFXBRWOHtxjWPC0Z8zPspsih7ny2Bn5UMbHhB3ENYkkgLPyJ5Cwbu3ek6X42xzeVM6o/af7qplN7mXk2ydXCxB210mzF4zJYPlJQJHit4K8OVmmQiXRfYOIL0pGKk4yxCEff0SA3xDeSaKtTaDApQoD442w+Nzmy7aSWJnNHcNdiiMr2nB4MVy4kXsF8CNb91IpulMlWLf+X/Nek=,iv:bPzJr/1eGT6VUoIi9FLp3DaXMRU48OlQs9r2hJDvH08=,tag:5FrnhA0FVBCISiSojYhWuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-23T12:34:18Z"
    mac: ENC[AES256_GCM,data:xrA/+N6wGNVgwl27XYO81YVb7dtgkclOpxJgOPj5AroqpNy+Z2lz6b4PfYvQTYlewkI5ambX7z6RuCkzKLSaacT5a29MVEhtKoKl+p85DB35pQnXqjxF9f4NhJezoTYq52fn/C8gxahAjYE+jfzry5lcB3X6KAHcp2sSV/046k8=,iv:y7hjf1R8Cb2j8cuPurLlESgrqRMzJ+ANcgfrUwILqHM=,tag:YumC2D7dGUCgJ/vae+inng==,type:str]
    pgp:
        - created_at: "2023-06-01T12:37:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAxDrDE6S/SFjAQv+NBhKqMKdoBKn35aA57+0lU77wUURjL8h/B4DXrrqWdtG
            TU3XIkQw8VMkzyk58ll3qEdv4dmk+uuKPkxmFoKApQGGQB9ktilB7cMmEddOHgtb
            hRn0SWq0bP1eNBcopmi8gRDBZn/f7D2Qxr9xW6LD4q2IbefCYM/bxx3ocJkgNBte
            wdrFz8dwFVmlt1QttAgg6gBAG8kx9fV9HPgHXtI2cgp0qnlBGo63xshnUlTr8ceZ
            T+9HCJm3B/SsU5KDZxVqVWb2nXyMMNrbVmmWwhTOEIwDQCTM0r8nPWnQy3Qe0Hky
            iHjCHB8xkI0yEbFGQ8br637vk+alXLeCeJU+FUhGy1lQjFVqBNkbc4XgmDcJgAU7
            uYKGpYTsBTrxlzujl6CH6cHq5+WGsL2ZyR34gc9Pr2CFZinGlPjH9K5AyvCu4137
            KuqTnFQAoq7zq1l8M/CsIgIkVZ5wrpAkcXtNOekkZ039PnKUQkDe+jbrE+1RwtjU
            z+2l5WfKWIUAfcL6ZKry1GgBCQIQ0mstvxHAqVUlBEJZLWhRrnhfEumBdWw3RXOQ
            v0W38um3tX8kX1IHjnQiS8LR48UPvtlxZxGlMuNvpapmpPvYzzUDFuaY7yhX1a2Q
            OUQD4Oo5U/UlxEZwoP6Oc0LN7x56a2oE3A==
            =W/+A
            -----END PGP MESSAGE-----
          fp: C92AE33AF20998F8CA09E819A842078E859DE4F1
    unencrypted_suffix: _unencrypted
    version: 3.8.1
