# Common default values for minio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

minio:
  enabled: true

  operator:
    image:
      pullPolicy: Always

  console: {}
