opentelemetry-ebpf-instrumentation:
  enabled: true

  fullnameOverride: opentelemetry-ebpf-instrumentation

  image:
    tag: v0.2.0

  config:
    data:
      otel_traces_export:
        endpoint: http://grafana-tempo.grafana:4317
      otel_metrics_export:
        endpoint: http://grafana-alloy.grafana.svc.cluster.local:4318

  serviceMonitor:
    enabled: true

    labels:
      release: prometheus-operator
