apiVersion: v1
kind: Secret
metadata:
  name: loki-datasources
  labels:
    grafana_datasource: 'true' # default value for: sidecar.datasources.label
stringData:
  loki.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://grafana-loki:3100
        jsonData:
          maxLines: 1000
          alertmanagerUid: alertmanager
          derivedFields:
            # Field with internal link pointing to Tempo data source in Grafana.
            # Supports both OpenTelemetry format (trace_id) and legacy format (traceID)
            - datasourceUid: tempo
              matcherRegex: '(?:trace_id|traceID)["\s:=]+([a-f0-9]{16,32})'
              name: TraceID
              # url will be interpreted as query for the datasource
              url: "$${__value.raw}"
